- name: Include distribution specific variables
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_facts.os_family }}-{{ ansible_facts.distribution_major_version }}.yml"
        - "{{ ansible_facts.distribution }}-{{ ansible_facts.distribution_version }}.yml"
        - "{{ ansible_facts.distribution }}.yml"
        - "{{ ansible_facts.os_family }}.yml"
      paths:
        - vars
  tags:
    - docker

- name: RHEL | Add Docker repositories
  yum_repository:
    file: "{{ docker_repo_file }}"
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.baseurl }}"
    enabled: "{{ item.enabled | default(omit) }}"
    gpgcheck: "{{ item.gpgcheck | default(omit) }}"
    gpgkey: "{{ item.gpgkey | default(omit) }}"
  loop: "{{ docker_yum_repositories[docker_edition | lower] }}"
  tags:
    - docker
    - yum
    - reposity
    - package

- name: RHEL | Install containerd.io
  dnf:
    name: https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.6-3.3.el7.x86_64.rpm
    state: present
    disable_gpg_check: yes
  when: ansible_facts.distribution_version is version('8' , '>=')
  tags:
    - docker
    - yum
    - package

- name: RHEL | Install Docker packages
  yum:
    name: "{{ docker_packages | union(docker_os_packages | default([])) }}"
    state: latest
  tags:
    - docker
    - yum
    - package
