- include_vars: Debian-old.yml
  when: ansible_facts.distribution_major_version is version('7', '<=')

- include_vars: Debian-new.yml
  when: ansible_facts.distribution_major_version is version('7', '>')

- name: DEBIAN | Check kernel version
  assert:
    msg: "Kernel version 3.10 or later is required. {{ ansible_facts.kernel }} is not supported"
    that:
      - ansible_facts.kernel.split('.')[:3] | join('.') is version('3.10', '>=')
  tags:
    - always
  when: ansible_facts.distribution_major_version is version('7', '<=')

- name: DEBIAN | Install preliminary packages
  apt:
    name: "{{ docker_os_packages }}"
    install_recommends: no
    state: present
    update_cache: yes
    cache_valid_time: 600
  tags:
    - docker
    - package

- name: DEBIAN | Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present
  tags:
    - docker
    - package

- name: DEBIAN | Add Docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_facts['distribution_release'] }} stable
    state: present
  tags:
    - docker
    - package

- name: DEBIAN | Install Docker packages
  apt:
    update_cache: yes
    cache_valid_time: 0
    name: "{{ docker_packages }}"
    install_recommends: no
    state: latest
  tags:
    - docker
    - package
