- name: Include distribution specific variables
  include_vars: "{{ ansible_facts.os_family }}.yml"
  tags:
    - docker

- include_tasks: "install-{{ ansible_facts.os_family }}.yml"
  tags:
    - docker

- name: Add users to docker group
  user:
    name: "{{ item }}"
    groups: "{{ docker_group }}"
    append: yes
  loop: "{{ docker_users }}"
  tags:
    - docker

- name: Install Docker Compose
  include_tasks: install-docker-compose.yml
  when: docker_compose_install
  tags:
    - docker
    - docker_compose
