- name: Include distribution specific variables
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_facts.os_family }}-{{ ansible_facts.distribution_major_version }}.yml"
        - "{{ ansible_facts.distribution }}-{{ ansible_facts.distribution_version }}.yml"
        - "{{ ansible_facts.distribution }}.yml"
        - "{{ ansible_facts.os_family }}.yml"
      paths:
        - vars
  tags:
    - docker

- name: Include distribution specific installation tasks
  include_tasks: install-{{ ansible_facts.os_family }}.yml
  tags:
    - docker

- name:  Configure daemon.json
  copy:
    content: "{{ docker_daemon_config | to_nice_json }}"
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644
  when: docker_daemon_config is not none
  notify: restart docker
  tags:
    - docker

- name:  Remove daemon.json
  file:
    path: /etc/docker/daemon.json
    state: absent
  when: docker_daemon_config is none
  notify: restart docker
  tags:
    - docker

- name: Start and enable Docker
  service:
    name: "{{ docker_service_name }}"
    state: started
    enabled: yes
  tags:
    - docker

- name: Add users to docker group
  user:
    name: "{{ item }}"
    groups: "{{ docker_group }}"
    append: yes
  loop: "{{ docker_users }}"
  tags:
    - docker

- name: Install Docker Compose
  include_tasks: install-docker-compose.yml
  when: docker_compose_install
  tags:
    - docker
    - docker_compose
