- hosts: all
  become: yes

  tasks:
    - debug:
        msg: >-
          Testing with Ansible {{ ansible_version.full }} using Python {{ ansible_facts.python_version }}
          on {{ ansible_facts.distribution }} {{ ansible_facts.distribution_version }}

    - debug:
        msg: 'Virt type: {{ansible_facts.virtualization_type}}, Service Manager: {{ansible_facts.service_mgr}}'
      tags: debug

    - name: Create test user
      user:
        name: docktu

    - import_role:
        name: docker
      vars:
        docker_users:
          - docktu
